apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: python
    spec:
      containers:
      - args:
        - sh
        - -c
        - sleep 5; SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_CAS_ADDR=4-2-1.scone-cas.cf
          SCONE_CONFIG_ID=FlaskSession-31684-14345-2245/flask_restapi python3
        image: application:v0.4
        imagePullPolicy: ""
        name: python
        ports:
        - containerPort: 4996
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
