
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: kumarsendhi/hello-python:v6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: GREETING
          value: howdy!
        resources:
          limits:
            sgx.k8s.io/sgx: 1

---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer